[project]
name = "swiftshadow"
version = "2.4.0"
description = "Free IP Proxy rotator for python"
readme = "README.md"
authors = [{ name = "sachin-sankar", email = "mail.sachinsankar@gmail.com" }]
requires-python = ">=3.10"
dependencies = [
  "aiofiles>=25.1.0",
  "aiohttp>=3.14.1",
  "appdirs>=1.4.4",
  "lxml>=6.1.1",
  "requests>=2.34.2",
]

[project.scripts]
swiftshadow = "swiftshadow:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
  "mkdocs>=1.6.1",
  "mkdocs-autolinks-plugin>=0.7.1",
  "mkdocs-material>=9.7.6",
  "mkdocstrings-python>=2.0.5",
  "pytest>=9.1.1",
  "ruff>=0.15.20",
  "tox>=4.56.1",
]
